## Inheritance

- A class can inherit from other class
- It improves code reuse
- Constructor, attributes and methods are inherited to child class
- Parent class has no access to the child class
- child class methods overrides the parent class methods
    - this is called method overriding
-```super()``` method is used to invoke parent class method and constructor

## Single heritance

In [8]:
class person:
    def __init__(self,name):
        self.name = name 
    def show(self):
        print(self.name + "is a python teacher")
class professor(person):
    def display(self):
        print("i am ",self.name)

In [9]:
per = professor("Jp_P@nchal")

In [10]:
per.name

'Jp_P@nchal'

In [11]:
per.show()

Jp_P@nchalis a python teacher


In [12]:
per.display()

i am  Jp_P@nchal


In [13]:
per1 = person("james")

In [14]:
per1.name


'james'

In [15]:

per.name

'Jp_P@nchal'

## Multilevel inheritance

In [17]:
class human:
    def __init__(self,name):
        self.name = name
    def show(self):
        print(self.name)

class person(human):
    pass
class professor(person):
    pass

In [18]:
p = professor("jp")

In [19]:
p.name

'jp'

In [20]:
p.show()

jp


## Multiple Inheritance

In [22]:
class person:
    def __init__(self,name):
        self.name = name
    def show(self):
        print(self.name)
class teacher:
    def credit(self):
        print("He teaches python")
class PythonProgrammer(person,teacher):
    pass

In [23]:
p1 = PythonProgrammer("jp1")

In [24]:
p1.credit()

He teaches python


In [25]:

p1.name

'jp1'

In [26]:
p1.show()

jp1


## Hiearchical Heritance

In [28]:
class Human:
    def __init__(self,name):
        self.name = name
    def show(self):
        print(self.name + "is a Professor")
class PythonProgrammer(Human):
    pass
class JavaProgrammer(Human):
    pass

In [29]:
p = PythonProgrammer("JP")

In [30]:
p.show()

JPis a Professor


In [31]:
j = JavaProgrammer("James ")

In [32]:
j.show()

James is a Professor



# Constructor Overriding

In [39]:
class Father:
    def __init__(self):
        self.money = 10000
        print("Father class constructor")
    def show(self):
        print("Person class method")
class Son(Father):
    def __init__(self):
        self.money = 500
        self.car = "BMW"
        print("Son class constructor")
    def display(self):
        print("Son class method")
        

In [40]:
s = Son()

Son class constructor


In [41]:
s.money

500

In [42]:
f = Father()

Father class constructor


In [43]:
f.money

10000

## `super() method`

- If we write constructor in both parent and child class, the parent class is not available in child class 
- `super()` methods is used to call parent class from the child

In [48]:
class phone:
    def __init__ (self,price,brand,camera):
        print("inside phone class")
        self.price = price
        self.brand = brand
        self.camera = camera
    def buy(self):
        print("Buying phone")
class smartphone(phone):
    def buy(self):
        print("Buying smartphone")
        super().buy()

In [50]:
s = smartphone(20000,"iphone",13)

inside phone class


In [51]:
s.buy()

Buying smartphone
Buying phone


# Polymorphism

- condition of occurence in difference in different forms
- At operator lvl
- At function lvl
- At method lvl

### Example

In [53]:
class car:
    def start(self):
        print("Engine Strated")
    def move(self):
        print("car is running")
    def stop(self):
        print("Breaks applied")
class clock:
    def move(self):
        print("Tick Tick Tick")
    def stop(self):
        print("Person is moving")
class Person:
    def move(self):
        print("person is moving")
    def stop(self):
        print("Person is moving")
        

In [57]:
c = car()
cl = clock()
p = Person()

In [58]:
def dosomthing(x):
    x.move()
    x.stop()

## ABSTRACT CLASS
- A class derived from ABC class Which belongs to abc module is known as abstract class in python.
- ABC class is known as meta class which means class that defines behaviour of other classes.
- Abstract class can have concrete and abstract methods
- Abstract class needs to be extended and its methods implemented
- one can't create object of an abstract class


In [1]:
from abc import ABC, abstractmethod

In [2]:
class Defenceforce(ABC):
    
    def __init__ (self):
        self.id = 101
        
    def area(self):
        pass
    def gun(self):
        print("The Gun is AK 47")

In [10]:
class Army(Defenceforce):
    def area(self):
        print("Area is land",self.id)

In [11]:

d = Army()

In [12]:
d.area()

Area is land 101


In [13]:
d.gun()

The Gun is AK 47


In [15]:
d.id

101

In [20]:
class Navy(Defenceforce):
    def area(self):
        print("Area is land",self.id)

In [21]:
a = Navy()

In [22]:
a.area()

Area is land 101


In [23]:
a.gun()

The Gun is AK 47


## Create an abstract class shape with abstract method `calculate_area`. Create two class Rectangle and circle inheriting from shape. create two objects of rectangle and circle and find the area of these objects.

## 632


In [35]:
class book:
    def __init__(self,name , n , authors,publisher,ISBN,year):
        self.name = name
        self.n = n
        self.authors = authors
        self.publisher =publisher
        self.ISBN = ISBN
        self.year = years
    def dispaly():
        print(self.name)
        print(self.n)
        print(self.publisher)
        print(self.ISBN)
        print(self.year)
        
        
        
        

In [34]:
class Derivedbook(book):
    def __init__(self,name , n , authors,publisher,ISBN,year):
        super().__init()
        self.course = course
    def display(self):
        print(self.name)
        print(self.n)        
        print(self.authors)        
        print(self.publisher)        
        print(self.ISBN)
        print(self.year)                

## METHOD RESOLUTION OREDER IN PYHTON
- It defines an order in which the class is searched in case of multiple inheritance.
- It is based on C3 Linearization Algorithm(>= Python 2.3)

## C3 Linearization Algorithm
**Notation**

- For a list of classes-C1C2C3...Cn
    - the C1 is the head of class and the rest is tall
- C3 Linearization Algorithm is defined as MRO of sum of any class C and the linear of Parents and the list of parents
```
    L(C(B1,B2...Bn)) = C + merge(L(B1),L(B2),...Bn))
```
- Here B1 to Bn are the parent classes of C

1. Take the head of list L(B1) from left to right
2. If the head of selected class is not in tail of the list , add it to the linear and remove it from the list.
3. Repeat the process untill the classes are removed or it impossible to find good head.



In [1]:
!python --version

Python 3.8.5


In [2]:
##

In [3]:

class F:
    pass
class E:
    pass
class D:
    pass
class C(D,F):
    pass
class B(D,E):
    pass
class A(B,C):
    pass


In [5]:
A.mro()

[__main__.A,
 __main__.B,
 __main__.C,
 __main__.D,
 __main__.E,
 __main__.F,
 object]

## First Step 
- MRO OF D,E,F,O
- L(D) = DO
- L(E) = EO
- L(F) = FO
- L(O) = O

## Second Step
```
L(C) = C+ merge(L(D),L(F),DF)
     = C + merge(DO,FO,DF)
     = C + D + merge(O,FO,F)
     = C + D + F + O
     = CDFO
```

## Third Step
```
L(B) = B + merge(L(D),L(E),DE)
     = B + MERGE(DO, EO, DE)
     = B + D + MERGE(O, EO, E)
     = B + D + E + O
     = BDEO
````

## Four Step
```
L(A) = A + MERGE(L(B),L(C),BC)
     = A + MERGE(BDEO,CDFO,BC)
     = A + B + MERGE(DEO , CDFO , C)
     = A + B + C + MERGE(DEO, DFO)
     = A + B+ C + D + MERGE(EO, FO)
     = A + B+ C + D + E + F + O
```

## 604
```
What will be the MRO for class P in program given below:
class A:
    pass
class B:
    pass
class C:
    pass
class X(A,B):
    pass
class Y(C,A,B):
    pass
class Z(A):
    pass
class P(Z,Y,X):
    pass
```

In [10]:
class A:            #AO
    pass
class B:            #BO
    pass
class C:            #CO
    pass
class X(A,B):       #XABO
    pass
class Y(C,A,B):     #YCABO
    pass
class Z(A):         #ZAO
    pass
class P(Z,Y,X):     # P + MERGE(ZAO,YCABO,XABO,ZYX) 
    pass

In [11]:
P.mro()

[__main__.P,
 __main__.Z,
 __main__.Y,
 __main__.C,
 __main__.X,
 __main__.A,
 __main__.B,
 object]

## 656
```
Find the MRO of class Z of below program:
class A: pass
class B: pass
class C: pass
class D:pass
class E:pass
class K1(C,A,B): pass
class K3(A,D): pass
class K2(B,D,E): pass
class Z( K1,K3,K2): pass
```

In [12]:
class A:                #AO
    pass
class B:                #BO
    pass
class C:                #CO
    pass
class D:                #DO
    pass
class E:                #EO
    pass
class K1(C,A,B):        #K1CABO
    pass
class K3(A,D):          #K1ADO
    pass
class K2(B,D,E):        #K1BDEO
    pass
class Z( K1,K3,K2):     #ZK1CK3AK2BDEO
    pass

In [15]:
class A:
    pass 
class B:
    pass
class C(A,B): 
    pass 
class D(B,A): 
    pass 
class E(C,D): 
    pass 


TypeError: Cannot create a consistent method resolution
order (MRO) for bases A, B

## OPERATOR OVERLOADING
```
__add__ = +
__sub__ = -
__mul__ = *
__truediv__ = /
```

In [17]:
class Fraction:
    
    def __init__(self,x,y):
        self.num = x
        self.den = y
    
    def __add__(self,other):
        new_num = self.num*other.den + other.num*self.den
        new_den = self.den * other.den
        return f"{new_num}/{new_den}"
    
    def __sub__(self,other):
        new_num = self.num*other.den - other.num*self.den
        new_den = self.den * other.den
        return f"{new_num}/{new_den}"
    
    def __mul__(self,other):
        new_num = self.num*other.num 
        new_den = self.den * other.den
        return f"{new_num}/{new_den}"
    
    def __truediv__(self,other):
        new_num = self.num*other.den 
        new_den = self.den * other.num
        return f"{new_num}/{new_den}"
    
        
        

In [18]:
f1 = 1/13
f2 = 1/12

In [22]:
f1 = Fraction(1,3)

In [23]:
f2  = Fraction(2,3)

In [25]:
f.__add__(f2)

'9/9'

## Comparison Operators
```
__eq__ -> ==
__lt__ -> <
__gt__ -> >
```

## WAP to create a class Data with data member value. Create twp objects of the class to demonstrate comparison operators

In [37]:
# Define the class
class Data:
    def __init__(self, value):
        self.value = value

    # Comparison operators
    def __eq__(self, other):
        return self.value == other.value

    
    def __lt__(self, other):
        return self.value < other.value

    def __gt__(self, other):
        return self.value > other.value

obj1 = Data(4)
obj2 = Data(10)

print("obj1 == obj2:", obj1 == obj2)   # False
print("obj1 < obj2 :", obj1 < obj2)    # True
print("obj1 > obj2 :", obj1 > obj2)    # False




obj1 == obj2: False
obj1 < obj2 : True
obj1 > obj2 : False


In [38]:
class Student:
    def __init__(self,name,email):
        self.name = name
        self.email = email
    def putdata(self):
        print(self.name)
        print(self.email)
class PhDGuide:
    def __init__(self,name,email):
        self.name = name
        self.email = email
        self.Students = []
        
    def put_data(self):
        print("guide name",self.name)
        print("guide email ",self.email)        
        print("Students under guide")        
            
        for student in self.students:
            student.putdata()
            print("----")
            
    def add(self          )

SyntaxError: unexpected EOF while parsing (<ipython-input-38-e6efd02a8508>, line 1)

## Numpy

In [1]:
import numpy as np

In [2]:
np.info

<function numpy.info(object=None, maxwidth=76, output=<ipykernel.iostream.OutStream object at 0x000002ACF58E5D90>, toplevel='numpy')>

In [4]:
np.array??

In [5]:
arr = np.array([1,2,3,5])

In [7]:
print(arr)

[1 2 3 5]


In [9]:
print(type(arr))

<class 'numpy.ndarray'>


In [12]:
print(np.__version__)

1.19.2


## 2D Array

In [16]:
b= np.array([[1,2,3],[4,5,6]])

In [17]:
print(b)

[[1 2 3]
 [4 5 6]]


## 3D Array

In [18]:
c = np.array([[1,2],[2,3],[3,4]])
print(c)

[[1 2]
 [2 3]
 [3 4]]


In [19]:
c = np.array([[[1,2],[3,4],]])
print(c)

[[[1 2]
  [3 4]]]


# # dtype

In [21]:
c.dtype

dtype('int32')

In [22]:
arr = np.array([1,2,3,0,0],dtype = bool)

In [23]:
print(arr)

[ True  True  True False False]


## Array Attribute

### ndim

In [33]:
a1 = np.array([0,1,2,3,4,5,6,7,8,9])

In [ ]:
a2 = np.arange(10)

In [45]:
a = np.array([1,2,3,5])
b = np.array([[1,2,3],[4,5,6]])
c = np.array([[[1,2],[7,8]]])
print(a)
print(b)
print(c)


[1 2 3 5]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [7 8]]]


In [35]:
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [36]:
print(a2)

[0 1 2 3 4 5 6 7 8 9]


In [37]:
a1.ndim # it shows the dimension

1

### shape - to check the shape

In [40]:
a1.shape #it gives no.of cols and rows

(10,)

### size of the array

In [41]:
a1.size

10

### itemsize - size in bytes of an array item

In [42]:
a1.itemsize

4

### dtype

In [43]:
a1.dtype

dtype('int32')

### Reshape
- to change the dimension

In [46]:
a1 = np.arange(12).reshape(3,4)

In [47]:
print(a1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [48]:
a1 = np.arange(12).reshape(3,3)

ValueError: cannot reshape array of size 12 into shape (3,3)

In [49]:
a1 = np.arange(12).reshape(2,6)

In [51]:
print(a1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


### Scalar operation

In [53]:
print(a1*2)
print()
print(a1/2)
print()
print(a1//2)
print()
print(a1**2)




[[ 0  2  4  6  8 10]
 [12 14 16 18 20 22]]

[[0.  0.5 1.  1.5 2.  2.5]
 [3.  3.5 4.  4.5 5.  5.5]]

[[0 0 1 1 2 2]
 [3 3 4 4 5 5]]

[[  0   1   4   9  16  25]
 [ 36  49  64  81 100 121]]


### np.short
- Returns a sorted copy of an array

In [57]:
a = np.array([58,67,12,45,53,89,93])

In [59]:
np.sort(a)[::-1]

array([93, 89, 67, 58, 53, 45, 12])

In [56]:
a

array([58, 67, 12, 45, 53, 89, 93])

### np.concatenate
- it concatenates a sequance of arrays along the existing axis

In [67]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [68]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

## COPY list

### np.nditer

In [60]:
a = np.array([58,67,12,45,53,89,93])

In [61]:
for i in a:
    print(i)

58
67
12
45
53
89
93


In [62]:
a = np.array([1,2,3,5])
b = np.array([[1,2,3],[4,5,6]])
c = np.array([[[1,2],[7,8]]])


In [63]:

for i in b:
    print(i)

[1 2 3]
[4 5 6]


In [65]:
for i in np.nditer(b):
    print(i,end = " ")

1 2 3 4 5 6 

### np.where
- It returns the indices of elements in an i/p array where the given condition is satisfied

In [69]:
a = np.array([56,68,23,11,78,86,34,51,50])

In [77]:
np.where(a>50)

(array([0, 1, 4, 5, 7], dtype=int64),)

In [78]:
np.where(a>50,0, a)

array([ 0,  0, 23, 11,  0,  0, 34,  0, 50])

In [79]:
a

array([56, 68, 23, 11, 78, 86, 34, 51, 50])

## Spiltting Arrays
- it is reverse of joining 
- it breaks array into multiple arrays
- ```array_split``` is used with number of spilt as parameters to spilt the array

In [80]:
import numpy as np

In [81]:
arr = np.array([1,2,3,4,5,6,7])

In [85]:
np.array_split(arr,3)

[array([1, 2, 3]), array([4, 5]), array([6, 7])]

### random in numpy

 ### randint

In [86]:
from numpy import random

In [88]:
x = random.randint(100)
print(x)

60


### rand


### 1d array

In [89]:
from numpy import random

In [90]:
x  = random.randint(100,size = (5))
print(x)

[ 4 59 75 63 12]


## 2D array

In [91]:
from numpy import random

In [94]:
x = random.randint(100,size=(3,5))

In [95]:
print(x)

[[48 15 50 30 89]
 [41 14 53 67  9]
 [12 77 78 66 44]]


In [99]:
from numpy import random
x = random.rand(5)
print(x)

[0.93604495 0.93812749 0.54263696 0.58426155 0.836747  ]


In [100]:
from numpy import random
x = random.rand(3,5)
print(x)


[[0.58243507 0.66055655 0.62902307 0.12019458 0.24214151]
 [0.46305889 0.9972336  0.73433988 0.08110704 0.32168719]
 [0.01863804 0.54126448 0.52236602 0.24441842 0.93887067]]


### choice method
- it allows you to generate a random value based on array

In [101]:
x = random.choice([3,5,6,7,8])
print(x)

6


In [ ]:
from numpy import random